CREATE OR REPLACE DATABASE PG_WINDOW_FUNCTIONS;
USE PG_WINDOW_FUNCTIONS;

DROP DATABASE AJ_WINDOW_FUNCTIONS;

CREATE OR REPLACE TABLE PG_EMPLOYEE_RAW
(
Employee_ID INT references TempRankedEmployees(Employee_ID) ON DELETE CASCADE ON UPDATE CASCADE ,
Name Varchar(20),
Salary INT
);

INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (100,'JENIFER',4400);
INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (100,'JENIFER',4400);
INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (101,'Michael',13000);
INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (101,'Michael',13000);
INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (102,'Pat',6000);
INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (102,'Pat',6000);
INSERT INTO PG_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (103,'Den',11000);

SELECT * FROM PG_EMPLOYEE_RAW;

-- ORDER BY IS NOT MANDATORY UNLIKE SNOWFLAKE IN MYSQL
select *,ROW_NUMBER() OVER( ORDER BY EMPLOYEE_ID) AS R_NUMBER FROM PG_EMPLOYEE_RAW;

DELETE FROM 
(
   SELECT *,ROW_NUMBER() OVER(ORDER BY SALARY) AS R_NUMBER FROM AJ_EMPLOYEE_RAW AS TEST
)   
WHERE TEST.R_NUMBER IN (2,5,7);

CREATE  OR REPLACE TEMPORARY TABLE TempRankedEmployees AS
SELECT *, ROW_NUMBER() OVER (ORDER BY EMPLOYEE_ID) AS R_NUMBER
FROM PG_EMPLOYEE_RAW;
DELETE FROM TempRankedEmployees
WHERE R_NUMBER IN (2, 5, 7);

SELECT * FROM TempRankedEmployees;
DROP TABLE TempRankedEmployees;


ALTER TABLE PG_EMPLOYEE_RAW
ADD COLUMN  AS SELECT*, ROW_NUMBER() OVER(ORDER BY SALARY) AS R_NUMBER
FROM PG_EMPLOYEE_RAW;

DELETE FROM PG_EMPLOYEE_RAW
WHERE (EMPLOYEE_ID) IN (
    SELECT EMPLOYEE_ID
    FROM TempRankedEmployees
    WHERE R_NUMBER IN (2, 5, 7)
);
